#开启模板缓存（默认值：true）
spring:
  thymeleaf:
    cache: true
  #Check that the template exists before rendering it.
    check-template: true
  #检查模板位置是否正确（默认值:true）
    check-template-location: true
  #Content-Type的值（默认值：text/html）
    servlet:
      content-type: text/html
  #开启MVC Thymeleaf视图解析（默认值：true）
    enabled: true
  #模板编码
    encoding: UTF-8
  #要被排除在解析之外的视图名称列表，用逗号分隔
    excluded-view-names:
  #要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
    mode: HTML5
  #在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
    prefix: classpath:/templates/
  #在构建URL时添加到视图名称后的后缀（默认值：.html）
    suffix: .html
  #Thymeleaf模板解析器在解析器链中的顺序。默认情况下，它排第一位。顺序从1开始，只有在定义了额外的TemplateResolver Bean时才需要设置这个属性。
    template-resolver-order:
#  #可解析的视图名称列表，用逗号分隔
#    view-names:

#spring:
#  thymeleaf:
#    enabled: true  #开启thymeleaf视图解析
#    encoding: utf-8  #编码
#    prefix: classpath:/templates/  #前缀
#    cache: false  #是否使用缓存
#    mode: HTML  #严格的HTML语法模式
#    suffix: .html  #后缀名
